### PR TITLE
Usb german translation

### PR DESCRIPTION
**Pull request by paesku**
Added german translations for USB restore and unified translation for the term 'drive' ;-)

### CODE REVIEW

**Comment by linusbobcat** [comment]
Thanks for getting back. I don't think "Restore USB Drive" should be translated though. That's the name that people will see the app as in Finder regardless of the localization the Mac is in. I haven't found a way for the app itself to show a different name in different languages in Finder yet. Otherwise, it looks god!

**Comment by paesku** [comment]
I renamed titles for both apps since they wont be translated anyway.

**Comment by linusbobcat** [comment]
I'm sorry, but you've misinterpreted my statement. I meant that `"Restore USB Drive"` in the string `InstallComplete` of "Create elementary OS Installer" shouldn't be translated. The rest of it should.

**Comment by paesku** [comment]
Ah snap! now I got it. Reverted naming to match app name :-)

**Comment by linusbobcat** [comment]
Perfect. Thanks for your contribution!

**Comment by linusbobcat** [comment]
Hi, I moved my translations to [Transifex](https://www.transifex.com/create-elementary-os-installer) with new text, and I would like if you could offer German translations. Transifex doesn't require any pesky PRs and accepts Github logins. Read my [Translation Guide](https://github.com/linusbobcat/create-elementary-os-installer/wiki/Translations) for more info.

**Pull request merged**
