### PR TITLE
Update Localizable.strings

### PR DESCRIPTION
**Pull request by ghost**
Thank you for this lovely app :)

### CODE REVIEW

**Comment by linusbobcat** [comment]
Looks good to me. Thanks for your translation!

I'll credit you on my Github page later.

**Comment by linusbobcat** [comment]
Hi. I've updated the app with a new tool to restore USB drives on OS X El Capitan and above. In addition, I've updated "Create elementary OS Installer" with a new piece of UI text. I'd appreciate if you could help out with translating the new app and that new string.

**Comment by ghost** [comment]
Sure, I would do it, but I don't know where to do it 
Can you give me the link?

**Comment by linusbobcat** [comment]
The new app is in the same repo as this one. Just reclone this one and make the changes on both of them. "Restore USB Drive" needs to have complete Korean translations while "Create elementary OS Installer" just needs `InstallComplete` changed to mention the "Restore USB Drive" app. To see how it's suppose to look like, just open up the English language file. Don't translate the words "Restore USB Drive" though, because that's how the app will show up like in Finder (the file manager) regardless of translations.

**Comment by ghost** [comment]
I leave this link for me myself :)
https://github.com/linusbobcat/create-elementary-os-installer/tree/master/Create%20elementary%20OS%20Installer.app/Contents/Resources

**Pull request merged**
