### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by paesku**
I added German translations for the OS GUI.

### CODE REVIEW

**Comment by linusbobcat** [comment]
Looks good. Thanks for your contribution! I'll credit you in my readme.

**Comment by paesku** [comment]
Hi @linusbobcat! After reading your contribution section within the readme I'm not quite sure if I missed a folder like: de.lproj ?
Thank you anyways for the installer tool. It worked and now I'm running a pretty nice elementary OS!

**Comment by linusbobcat** [comment]
The German translations do completely work in El Capitan. I actually checked the language codes for Finder, and that too only contains German.lproj. I'll probably duplicate that folder into de.lproj just in case.

**Comment by linusbobcat** [comment]
Hi. I've updated the app with a new tool to restore USB drives on OS X El Capitan and above. I'd appreciate if you could help out with translating the new app.

**Comment by paesku** [comment]
@linusbobcat I will hook on that this weekend …

**Pull request merged**
