### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by GilDev**
Hope it will be useful. =)

### CODE REVIEW

**Comment by linusbobcat** [comment]
Thanks for your contribution! I'll credit you in the README.

**Comment by linusbobcat** [comment]
Hi. What would be the proper French translation for text "Create elementary OS Installer"? I found a way to localize appnames in Finder and would like your input instead of going to Google Translate way.

**Comment by GilDev** [comment]
The best would be « Créer un installeur Elementary OS » and for « Restore USB drive » it would be « Restaurer un disque USB », although "restore" seems a bit weird to me, even in english. Would'nt "erase" be better?
Don't go to Google Translate, just ask me whatever you need, I will be happy to help =)

**Comment by linusbobcat** [comment]
In English, I used “Restore” to mean “restore” the USB drive to normal. I’ll update the translations myself. Thanks for your help!

Regards,
Linus Bobcat

**Comment by GilDev** [comment]
Yes it's the same in french but it felt kind of weird, but works best for beginners I guess
Best regards, feel free to ask more,
GilDev

**Comment by linusbobcat** [comment]
Hi, I moved my translations to [Transifex](https://www.transifex.com/create-elementary-os-installer) with new text, and I would like if you could offer French translations. Transifex doesn't require any pesky PRs and accepts Github logins. Read my [Translation Guide](https://github.com/linusbobcat/create-elementary-os-installer/wiki/Translations) for more info.

**Comment by GilDev** [comment]
Done!

**Pull request merged**
