### PR TITLE
Update portuguese translation

### PR DESCRIPTION
**Pull request by leonardo-lemos**
Create portuguese translation and update the strings file.

### CODE REVIEW

**Comment by linusbobcat** [comment]
Looks good to me. Thanks for your translation!

I'll credit you on the Github page later.

**Comment by linusbobcat** [comment]
Hi. just to confirm, is this translation Portugese, or Brazilian Portugese?

**Comment by leonardo-lemos** [comment]
Brazilian Portuguese.
Em 27/11/2015 20:21, linusbobcat notifications@github.com escreveu:Hi. just to confirm, is this translation Portugese, or Brazilian Portugese?

**Comment by linusbobcat** [comment]
How compatible is Portugese with Brazillian Portugese? Could I use the same translations or not?

**Comment by leonardo-lemos** [comment]
There aren't differences in these strings.
Em 27/11/2015 20:26, linusbobcat notifications@github.com escreveu:How compatible is Portugese with Brazillian Portugese? Could I use the same translations or not?

**Comment by linusbobcat** [comment]
Cool, then I'll use the same translations for both.

**Comment by linusbobcat** [comment]
Hi. I've updated the app with a new tool to restore USB drives on OS X El Capitan and above. I'd appreciate if you could help out with translating the new app.

**Pull request merged**
